// Auto-generated by Portfolio Generator SaaS
// Edit this file to customise your portfolio data

export interface NavItem { label: string; targetId: string; }
export interface ExpertiseItem {
  id: string; num: string; name: string; desc: string;
  type: "dna" | "neural" | "mandala" | "network" | "atom" | "spectrum";
}
export interface ProjectItem {
  id: string; num: string; cat: string; flip: boolean;
  titlePrefix: string; titleHighlight: string; titleSuffix?: string;
  img: string; desc: string; tech: string[]; link: string;
}
export interface TrainingItem { title: string; org: string; desc: string; active: boolean; }
export interface HackathonItem { name: string; date: string; desc: string; }
export interface StatItem { n: string; l: string; }
export interface SocialLink { label: string; url: string; isDownload?: boolean; }
export interface CustomSectionItem { id: string; heading: string; subheading?: string; body?: string; icon?: string; url?: string; }
export interface CustomSection { id: string; type: string; title: string; visible: boolean; items: CustomSectionItem[]; }

export const portfolioData = {
  backgroundAnimation: "dna",
  colorPalette: "neon-lime",
  customAccentColor: "",
  personal: {
  "name": "Aziz Said",
  "firstName": "AZIZ",
  "lastName": "SAID",
  "logoText": "AS",
  "role": "Fullstack",
  "availabilityText": "Open to Work",
  "tagline": "Portfolio — 2025 / 2026",
  "education": "Esprit",
  "heroDescription": "Crafting intelligent, scalable digital systems.",
  "heroSubTextLine1": "Full-Stack Developer crafting",
  "heroSubTextLine2": "Full stack",
  "primaryCtaText": "View Work",
  "secondaryCtaText": "Let's Talk",
  "scrollText": "Scroll",
  "email": "laaziz.laaziz132@gmail.com",
  "photoUrl": "",
  "photoPosition": "right",
  "cvUrl": ""
},

  seo: {
  "title": "Aziz Said — Fullstack",
  "description": "Portfolio of Aziz Said — Fullstack",
  "ogTitle": "Aziz Said — Portfolio",
  "ogDescription": "Fullstack"
},

  navigation: [
    { label: "Expertise", targetId: "tiles" },
    { label: "Work", targetId: "projects" },
    { label: "About", targetId: "about" },
    { label: "Timeline", targetId: "experience" },
    ...[{"label":"Testimonials","targetId":"section-cs-1790939031477"}],
    { label: "Contact", targetId: "contact" },
  ] as NavItem[],

  marquee: ["react","python","react","python"],

  expertiseHeader: {
  "titleMain": "Core",
  "titleAccent": "Expertise",
  "badge": "2 Domains"
},

  expertise: [
  {
    "id": "tile-1790938819711",
    "num": "01",
    "desc": "React",
    "name": "React",
    "type": "dna"
  },
  {
    "id": "tile-1790938836564",
    "num": "02",
    "desc": "React",
    "name": "React",
    "type": "network"
  }
] as ExpertiseItem[],

  projectsHeader: {
  "titleMain": "Deployed",
  "titleAccent": "Systems"
},

  projects: [
  {
    "id": "pc-1790938844135",
    "num": "01 / 02",
    "cat": "React",
    "flip": false,
    "titlePrefix": "React",
    "titleHighlight": "React",
    "titleSuffix": "React",
    "img": "https://res.cloudinary.com/dhlnfpfen/image/upload/v1790938865/portfolio-assets/project-pc-1790938844135/l6yjhpf4c1yvylth0duk.jpg",
    "desc": "React",
    "tech": [
      "React"
    ],
    "link": "https://"
  },
  {
    "id": "pc-1790938878378",
    "num": "02 / 02",
    "cat": "React",
    "flip": true,
    "titlePrefix": "React",
    "titleHighlight": "React",
    "titleSuffix": "React",
    "img": "https://res.cloudinary.com/dhlnfpfen/image/upload/v1790938894/portfolio-assets/project-pc-1790938878378/ifwgwfxqvcyuk6s7nxii.png",
    "desc": "React",
    "tech": [],
    "link": "React"
  }
] as ProjectItem[],

  about: {
    ...{
  "statementLine1": "Building the",
  "statementHighlight": "intelligent",
  "statementLine2": "web, one",
  "statementLine3": "system at a time.",
  "paragraphs": [
    "vbhzebvjbakjbvkneavnkjaenvnkennlkez"
  ]
},
    stats: [
  {
    "l": "cpa",
    "n": "8.50"
  }
] as StatItem[],
  },

  timeline: {
    ...{
  "titleMain": "Track",
  "titleAccent": "Record",
  "trainingColumnTitle": "Training & Certifications",
  "hackathonsColumnTitle": "Hackathons"
},
    training: [
  {
    "org": "React",
    "desc": "React",
    "title": "React",
    "active": true
  },
  {
    "org": "React",
    "desc": "React",
    "title": "React",
    "active": true
  }
] as TrainingItem[],
    hackathons: [
  {
    "date": "React",
    "desc": "React",
    "name": "React"
  }
] as HackathonItem[],
  },

  contact: {
    ...{
  "label": "— Get in touch",
  "headingLine1": "Let's",
  "headingHighlight": "Build",
  "headingLine2": "Together",
  "email": "laaziz.laaziz132@gmail.com",
  "emailSubject": "Let's connect"
},
    socials: [
  {
    "url": "https://",
    "label": "github"
  }
] as SocialLink[],
  },

  footer: {
  "author": "Aziz Said",
  "logo": "AS.",
  "credit": "Designed & Built by Aziz Said"
},

  customSections: [
  {
    "id": "cs-1790939031477",
    "type": "testimonials",
    "items": [
      {
        "id": "cs-1790939031477-item-0",
        "url": "https://linkedin.com",
        "body": "An exceptional engineer with remarkable architectural rigor. Our real-time streaming infrastructure was deployed two weeks ahead of schedule with total reliability.",
        "heading": "Alexandre Moreau",
        "subheading": "VP Engineering @ Nexus AI"
      },
      {
        "id": "cs-1790939031477-item-1",
        "url": "https://linkedin.com",
        "body": "Rare product intuition coupled with complete mastery of 3D WebGL. The final delivery exceeded expectations and deeply impressed our investors.",
        "heading": "Elena Rostova",
        "subheading": "Head of Product @ QuantumLabs"
      }
    ],
    "title": "Testimonials",
    "visible": true
  }
] as CustomSection[],
};
